version: 2
jobs:
  build:
    docker:
      - image: huzhenghui/chuxin-generator-circleci:build-0.0.7
    steps:
      - run:
          name: Version Summary
          command: echo "Version - build-0.0.7"
      - run:
          name: CIRCLE_BUILD_NUM
          command: echo ${CIRCLE_BUILD_NUM}
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: ls -al /chuxin-generator
          command: ls -al /chuxin-generator
      - run:
          name: cd /chuxin-generator && git pull
          command: cd /chuxin-generator && git pull
      - run:
          name: cd /chuxin-generator && git submodule update --init
          command: cd /chuxin-generator && git submodule update --init
      - run:
          name: cd /chuxin-generator && git submodule update --remote
          command: cd /chuxin-generator && git submodule update --remote
      - run:
          name: cp --recursive --dereference --verbose /chuxin-generator/content-posts/* /chuxin-generator/gohugo-site/content/posts/
          command: cp --recursive --dereference --verbose /chuxin-generator/content-posts/* /chuxin-generator/gohugo-site/content/posts/
      - run:
          name: cd /chuxin-generator/gohugo-site && ln -s -f -T -v themes/huzhenghui-universal/exampleSite/data data
          command: cd /chuxin-generator/gohugo-site && ln -s -f -T -v themes/huzhenghui-universal/exampleSite/data data
      - run:
          name: cd /chuxin-generator/gohugo-site && ln -s -f -T -v themes/huzhenghui-universal/exampleSite/static static
          command: cd /chuxin-generator/gohugo-site && ln -s -f -T -v themes/huzhenghui-universal/exampleSite/static static
      - run:
          name: cd /chuxin-generator/gohugo-site && ./gohugo-generate.sh
          command: cd /chuxin-generator/gohugo-site && ./gohugo-generate.sh
      - run:
          name: cd /chuxin-generator/gohugo-site && ./gohugo-process-stdout.sh
          command: cd /chuxin-generator/gohugo-site && ./gohugo-process-stdout.sh
      - run:
          name: cd /chuxin-generator/gohugo-site && hugo -DEF
          command: cd /chuxin-generator/gohugo-site && hugo -DEF
      - add_ssh_keys:
          fingerprints:
            - "f7:96:af:f1:35:c9:03:a0:b7:1e:64:34:e0:8f:4a:31"
      - run:
          name: cd / && git clone git@github.com:chuxin-community/chuxin-community.github.io
          command: cd / && git clone git@github.com:chuxin-community/chuxin-community.github.io
      - run:
          name: cd /chuxin-community.github.io && cp --recursive --dereference --verbose /chuxin-generator/public-repository/docs/* .
          command: cd /chuxin-community.github.io && cp --recursive --dereference --verbose /chuxin-generator/public-repository/docs/* .
      - run:
          name: git config --global user.email "chuxin-community.github.com@daonao.com"
          command: git config --global user.email "chuxin-community.github.com@daonao.com"
      - run:
          name: git config --global user.name "chuxin-community"
          command: git config --global user.name "chuxin-community"
      - run:
          name: cd /chuxin-community.github.io && touch ${CIRCLE_BUILD_NUM}
          command: cd /chuxin-community.github.io && touch ${CIRCLE_BUILD_NUM}
      - run:
          name: cd /chuxin-community.github.io && git add --verbose .
          command: cd /chuxin-community.github.io && git add --verbose .
      - run:
          name: cd /chuxin-community.github.io && git commit -m 'generatoed document'
          command: cd /chuxin-community.github.io && git commit -m 'generatoed document'
      - run:
          name: cd /chuxin-community.github.io && ls -al .
          command: cd /chuxin-community.github.io && ls -al .
      - run:
          name: cd /chuxin-community.github.io && git push
          command: cd /chuxin-community.github.io && git push
