version: 2
jobs:
  info-job:
    docker:
      - image: huzhenghui/chuxin-generator-circleci:build-0.0.5
    steps:
      - checkout
      - run:
          name: Version Summary
          command: echo "Version - build-0.0.5"
      - run:
          name: Print the Current Time
          command: date
workflows:
  version: 2
  info-workflow:
    jobs:
      - info-job
