version: 2
jobs:
  build:
    docker:
      - image: huzhenghui/chuxin-generator-circleci:build-0.0.13
    steps:
      - run:
          name: Version Summary
          command: echo "Version - build-0.0.13"
      - run:
          name: CIRCLE_BUILD_NUM
          command: echo ${CIRCLE_BUILD_NUM}
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: ls -al /chuxin-generator
          command: ls -al /chuxin-generator
      - run:
          name: cd /chuxin-generator && git pull
          command: cd /chuxin-generator && git pull
      - run:
          name: cd /chuxin-generator && git submodule update --init
          command: cd /chuxin-generator && git submodule update --init
      - run:
          name: cd /chuxin-generator && git submodule update --remote
          command: cd /chuxin-generator && git submodule update --remote
      - run:
          name: cp --recursive --dereference --verbose /chuxin-generator/content-posts/* /chuxin-generator/gohugo-site/content/blog/
          command: cp --recursive --dereference --verbose /chuxin-generator/content-posts/* /chuxin-generator/gohugo-site/content/blog/
      - run:
          name: cd /chuxin-generator/gohugo-site && ln -s -f -T -v themes/huzhenghui-universal/exampleSite/data data
          command: cd /chuxin-generator/gohugo-site && ln -s -f -T -v themes/huzhenghui-universal/exampleSite/data data
      - run:
          name: cd /chuxin-generator/gohugo-site && ln -s -f -T -v themes/huzhenghui-universal/exampleSite/static static
          command: cd /chuxin-generator/gohugo-site && ln -s -f -T -v themes/huzhenghui-universal/exampleSite/static static
      - run:
          name: ls -al /chuxin-script
          command: ls -al /chuxin-script
      - run:
          name: cd /chuxin-generator/gohugo-site && /chuxin-script/gohugo-process-stderr.sh
          command: cd /chuxin-generator/gohugo-site && /chuxin-script/gohugo-process-stderr.sh
      - run:
          name: cd /chuxin-generator/gohugo-site && /chuxin-script/gohugo-process-stdout.sh
          command: cd /chuxin-generator/gohugo-site && /chuxin-script/gohugo-process-stdout.sh
      - run:
          name: cd /chuxin-generator/gohugo-site && hugo -DEF
          command: cd /chuxin-generator/gohugo-site && hugo -DEF
      - add_ssh_keys:
          fingerprints:
            - "74:9e:9c:5b:59:02:0d:ca:d0:bb:87:9c:02:df:e2:4f"
      - run:
          name: cd / && git clone git@github.com:chuxinshequ/chuxinshequ.github.io
          command: cd / && git clone git@github.com:chuxinshequ/chuxinshequ.github.io
      - run:
          name: ls -al /chuxin-generator/gohugo-site/public
          command: ls -al /chuxin-generator/gohugo-site/public
      - run:
          name: cd /chuxinshequ.github.io && cp --recursive --dereference --verbose /chuxin-generator/gohugo-site/public/* .
          command: cd /chuxinshequ.github.io && cp --recursive --dereference --verbose /chuxin-generator/gohugo-site/public/* .
      - run:
          name: git config --global user.email "chuxin-community.github.com@daonao.com"
          command: git config --global user.email "chuxin-community.github.com@daonao.com"
      - run:
          name: git config --global user.name "chuxin-community"
          command: git config --global user.name "chuxin-community"
      - run:
          name: cd /chuxinshequ.github.io && touch ${CIRCLE_BUILD_NUM}
          command: cd /chuxinshequ.github.io && touch ${CIRCLE_BUILD_NUM}
      - run:
          name: cd /chuxinshequ.github.io && git add --verbose .
          command: cd /chuxinshequ.github.io && git add --verbose .
      - run:
          name: cd /chuxinshequ.github.io && git commit -m 'generatoed document'
          command: cd /chuxinshequ.github.io && git commit -m 'generatoed document'
      - run:
          name: cd /chuxinshequ.github.io && ls -al .
          command: cd /chuxinshequ.github.io && ls -al .
      - run:
          name: cd /chuxinshequ.github.io && git push
          command: cd /chuxinshequ.github.io && git push
