version: 2
jobs:
  info-job:
    docker:
      - image: huzhenghui/chuxin-generator-circleci:build-0.0.5
    steps:
      - checkout
      - run:
          name: Version Summary
          command: echo "Version - build-0.0.5"
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: ls -al /chuxin-generator
          command: ls -al /chuxin-generator
  build-job:
    docker:
      - image: huzhenghui/chuxin-generator-circleci:build-0.0.5
    steps:
      - run:
          name: cd /chuxin-generator && git submodule update --init
          command: cd /chuxin-generator && git submodule update --init
      - run:
          name: cd /chuxin-generator && git submodule update --remote
          command: cd /chuxin-generator && git submodule update --remote
      - run:
          name: cp -RL /chuxin-generator/content-posts/* /chuxin-generator/gohugo-site/content/posts/
          command: cp -RL /chuxin-generator/content-posts/* /chuxin-generator/gohugo-site/content/posts/
      - run:
          name: cd /chuxin-generator/gohugo-site && ln -s -f -T themes/huzhenghui-universal/exampleSite/data data
          command: cd /chuxin-generator/gohugo-site && ln -s -f -T themes/huzhenghui-universal/exampleSite/data data
      - run:
          name: cd /chuxin-generator/gohugo-site && ln -s -f -T themes/huzhenghui-universal/exampleSite/static static
          command: cd /chuxin-generator/gohugo-site && ln -s -f -T themes/huzhenghui-universal/exampleSite/static static
      - run:
          name: cd /chuxin-generator/gohugo-site && ./gohugo-generate.sh
          command: cd /chuxin-generator/gohugo-site && ./gohugo-generate.sh
workflows:
  version: 2
  info-workflow:
    jobs:
      - info-job
      - build-job:
        requires:
          - info-job
        filters:
          branches:
            only: master
